### ISSUE TITLE
The "put" program seems to be missing

### ISSUE THREAD

**Issue by NightDeer** [yaobaiwei/GTran#2]
In **CMakeLists.txt** , there's a command "**add_subdirectory(put)**".
In [tutorial](https://github.com/yaobaiwei/GTran/blob/master/docs/Tutorial.md), it also says that we should upload graph data  onto HDFS by running **put** program.
Howerver, I can't find **put** program anywhere.

**Comment by yaobaiwei** [comment]
Sry for the mistake, you can find the **put** program in https://github.com/yaobaiwei/Grasper/tree/master/put
